
networks:
  microservice-net:
    driver: bridge
volumes:
  user-db-data:
  post-db-data:
  chat-db-data:
services:
  # ─── DATABASES ───────────────────────────────────────────────
  # post-db
  post-db:
    image: mysql:8.0
    container_name: post-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: post_db
    ports:
      - "3308:3306"
    volumes:
      - post-db-data:/var/lib/mysql
    networks:
      - microservice-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
    # chat-db
  chat-db:
    image: mysql:8.0
    container_name: chat-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_db
    ports:
      - "3309:3306"
    volumes:
      - chat-db-data:/var/lib/mysql
    networks:
      - microservice-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # user-db
  user-db:
    image: mysql:8.0
    container_name: user-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db

    ports:
      - "3307:3306"
    volumes:
      - user-db-data:/var/lib/mysql
    networks:
      - microservice-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - microservice-net
  #SERVICE
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservice-net
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8761/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 5


  user-service:
    env_file:
      - .env
    build: ./user-service
    container_name: user-service
#    ports:
#      - "8081:8080"
    environment:
      DB_HOST: user-db
      DB_NAME: user_db
      DB_USER: root
      DB_PASS: root
      EUREKA_URL: http://eureka-server:8761/eureka
      JWT_SECRET: 5ZVnyGvacZRrCczj+xnOJxKQlR1xIxeb52erVLM169U=
      REDIS_HOST: redis
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      user-db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - microservice-net

  post-service:
    build: ./post-service
    container_name: post-service

    environment:
      DB_HOST: post-db
      DB_NAME: post_db
      DB_USER: root
      DB_PASS: root
      EUREKA_URL: http://eureka-server:8761/eureka
      REDIS_HOST: redis
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      post-db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - microservice-net

  chat-service:
    build: ./chat-service
    container_name: chat-service

    environment:
      DB_HOST: chat-db
      DB_NAME: chat_db
      DB_USER: root
      DB_PASS: root
      EUREKA_URL: http://eureka-server:8761/eureka
      REDIS_HOST: redis
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      chat-db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - microservice-net

  # ─── GATEWAY ─────────────────────────────────────────────────
  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Dio.netty.resolver.dns.defaultSearchDomains="
      EUREKA_URL: http://eureka-server:8761/eureka
      JWT_SECRET: 5ZVnyGvacZRrCczj+xnOJxKQlR1xIxeb52erVLM169U=
      REDIS_HOST: redis
    depends_on:
      eureka-server:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - microservice-net
  #Kafla
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - microservice-net
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - microservice-net

