
networks:
  microservice-net:
    driver: bridge
volumes:
  user-db-data:
  post-db-data:
  chat-db-data:
  minio-data:
services:
  # ─── DATABASES ───────────────────────────────────────────────
  # post-db
  post-db:
    image: mysql:8.0
    container_name: post-db
    mem_limit: 256m
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: post_db
      MYSQL_INNODB_BUFFER_POOL_SIZE: 64M
    ports:
      - "3308:3306"
    volumes:
      - post-db-data:/var/lib/mysql
    networks:
      - microservice-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
    # chat-db
  chat-db:
    image: mysql:8.0
    container_name: chat-db
    mem_limit: 256m
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_db
      MYSQL_INNODB_BUFFER_POOL_SIZE: 64M
    ports:
      - "3309:3306"
    volumes:
      - chat-db-data:/var/lib/mysql
    networks:
      - microservice-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # user-db
  user-db:
    image: mysql:8.0
    container_name: user-db
    mem_limit: 256m
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
      MYSQL_INNODB_BUFFER_POOL_SIZE: 64M

    ports:
      - "3307:3306"
    volumes:
      - user-db-data:/var/lib/mysql
    networks:
      - microservice-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:alpine
    container_name: redis
    mem_limit: 64m
    command: redis-server --maxmemory 48mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    networks:
      - microservice-net

  minio:
    image: minio/minio:latest
    mem_limit: 256m
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: devlink_admin
      MINIO_ROOT_PASSWORD: devlink_secret_123
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - microservice-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 5

  #SERVICE
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservice-net
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8761/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 5


  user-service:
    env_file:
      - .env
    build: ./user-service
    mem_limit: 384m
    container_name: user-service
#    ports:
#      - "8081:8080"
    environment:
      JAVA_OPTS: "-Xms64m -Xmx256m -XX:+UseContainerSupport"
      DB_HOST: user-db
      DB_NAME: user_db
      DB_USER: root
      DB_PASS: root
      EUREKA_URL: http://eureka-server:8761/eureka
      JWT_SECRET: 5ZVnyGvacZRrCczj+xnOJxKQlR1xIxeb52erVLM169U=
      REDIS_HOST: redis
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      user-db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - microservice-net

  post-service:
    build: ./post-service
    container_name: post-service
    mem_limit: 500m
    env_file:
      - .env

    environment:
      JAVA_OPTS: "-Xms64m -Xmx256m -XX:+UseContainerSupport"
      DB_HOST: post-db
      DB_NAME: post_db
      DB_USER: root
      DB_PASS: root
      EUREKA_URL: http://eureka-server:8761/eureka
      REDIS_HOST: redis
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      MINIO_ENDPOINT: http://minio:9000
      MINIO_PUBLIC_ENDPOINT: http://localhost:9000
      MINIO_USER: devlink_admin
      MINIO_PASSWORD: devlink_secret_123
      MINIO_BUCKET: devlink-media
    depends_on:
      post-db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - microservice-net

  chat-service:
    build: ./chat-service
    container_name: chat-service

    environment:
      DB_HOST: chat-db
      DB_NAME: chat_db
      DB_USER: root
      DB_PASS: root
      EUREKA_URL: http://eureka-server:8761/eureka
      REDIS_HOST: redis
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      chat-db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - microservice-net

  # ─── GATEWAY ─────────────────────────────────────────────────
  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    mem_limit: 256m
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Dio.netty.resolver.dns.defaultSearchDomains="
      EUREKA_URL: http://eureka-server:8761/eureka
      JWT_SECRET: 5ZVnyGvacZRrCczj+xnOJxKQlR1xIxeb52erVLM169U=
      REDIS_HOST: redis
    depends_on:
      eureka-server:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - microservice-net
  #Kafla
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - microservice-net
    depends_on:
      - zookeeper
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "kafka:9092" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - microservice-net

